---
sidebar: sidebar 
permalink: ontap991fo_technical_resources.html 
keywords:  
summary:  
---
= Technische Ressourcen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


In diesem Abschnitt werden die technischen Ressourcen vorgestellt, die die in diesem Dokument genannten Funktionen detailliert beschreiben.



== Technische Berichte

* TR-4067: NetApp ONTAP NFS Best Practices and Implementation Guide
+
https://www.netapp.com/us/media/tr-4067.pdf["https://www.netapp.com/us/media/tr-4067.pdf"^]

* TR-4515: ONTAP AFF All-SAN-Array-Systeme
+
https://www.netapp.com/pdf.html?item=/media/10379-tr4515pdf.pdf["https://www.netapp.com/pdf.html?item=/media/10379-tr4515pdf.pdf"^]

* TR-4526: Revisionssicherer WORM-Storage mit NetApp SnapLock
+
https://www.netapp.com/pdf.html?item=/media/6158-tr4526pdf.pdf["https://www.netapp.com/pdf.html?item=/media/6158-tr4526pdf.pdf"^]

* TR-4569: Security Hardening Guide for ONTAP 9
+
https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf"^]

* TR-4571: NetApp FlexGroup Volumes Best Practices
+
https://www.netapp.com/us/media/tr-4571.pdf["https://www.netapp.com/us/media/tr-4571.pdf"^]

* TR-4597: VMware vSphere with ONTAP
+
https://www.netapp.com/us/media/tr-4597.pdf["https://www.netapp.com/us/media/tr-4597.pdf"^]

* TR-4598: FabricPool Best Practices
+
https://www.netapp.com/us/media/tr-4598.pdf["https://www.netapp.com/us/media/tr-4598.pdf"^]

* TR-4684: Implementieren und Konfigurieren moderner SANs mit NVMe/FC
+
https://www.netapp.com/pdf.html?item=/media/10681-tr4684.pdf["https://www.netapp.com/pdf.html?item=/media/10681-tr4684.pdf"^]

* TR-4678: Datensicherung und Backup - FlexGroup Volumes
+
https://www.netapp.com/us/media/tr-4678.pdf["https://www.netapp.com/us/media/tr-4678.pdf"^]

* TR-4689: Architektur und Design der MetroCluster IP-Lösung
+
https://www.netapp.com/us/media/tr-4689.pdf["https://www.netapp.com/us/media/tr-4689.pdf"^]

* TR-4705: Lösungsarchitektur und Design der NetApp MetroCluster Lösung
+
https://www.netapp.com/pdf.html?item=/media/13480-tr4705pdf.pdf["https://www.netapp.com/pdf.html?item=/media/13480-tr4705pdf.pdf"^]

* TR-4743: FlexCache im ONTAP
+
https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf["https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf"^]

* TR-4814: S3 in ONTAP Best Practices
+
https://www.netapp.com/pdf.html?item=/media/17219-tr4814pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17219-tr4814pdf.pdf"^]





== Podcasts

* Folge 288 des Tech OnTap Podcasts: ONTAP System Manager 9.9.1
+
https://soundcloud.com/techontap_podcast/episode-288-ontap-system-manager-991["https://soundcloud.com/techontap_podcast/episode-288-ontap-system-manager-991"^]


