---
sidebar: sidebar 
permalink: ontap98fo_technical_resources.html 
keywords:  
summary: Diese Seite enthält Links zu verschiedenen technischen Ressourcen zum Thema ONTAP 9.8. 
---
= Technische Ressourcen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


In diesem Abschnitt werden die technischen Ressourcen vorgestellt, die die in diesem Dokument genannten Funktionen detailliert beschreiben.



== Technische Berichte

* TR-4067: NetApp ONTAP NFS Best Practices and Implementation Guide
+
https://www.netapp.com/us/media/tr-4067.pdf["https://www.netapp.com/us/media/tr-4067.pdf"^]

* TR-4375: MetroCluster FC für ONTAP 9.7
+
https://www.netapp.com/us/media/tr-4375.pdf["https://www.netapp.com/us/media/tr-4375.pdf"^]

* TR-4569: Security Hardening Guide for ONTAP 9
+
https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf"^]

* TR-4571: NetApp FlexGroup Volumes Best Practices
+
https://www.netapp.com/us/media/tr-4571.pdf["https://www.netapp.com/us/media/tr-4571.pdf"^]

* TR-4597: VMware vSphere with ONTAP
+
https://www.netapp.com/us/media/tr-4597.pdf["https://www.netapp.com/us/media/tr-4597.pdf"^]

* TR-4598: FabricPool Best Practices
+
https://www.netapp.com/us/media/tr-4598.pdf["https://www.netapp.com/us/media/tr-4598.pdf"^]

* TR-4678: Datensicherung und Backup - FlexGroup Volumes
+
https://www.netapp.com/us/media/tr-4678.pdf["https://www.netapp.com/us/media/tr-4678.pdf"^]

* TR-4689: Architektur und Design der MetroCluster IP-Lösung
+
https://www.netapp.com/us/media/tr-4689.pdf["https://www.netapp.com/us/media/tr-4689.pdf"^]

* TR-4705: Lösungsarchitektur und Design der NetApp MetroCluster Lösung
+
https://www.netapp.com/pdf.html?item=/media/13480-tr4705pdf.pdf["https://www.netapp.com/pdf.html?item=/media/13480-tr4705pdf.pdf"^]

* TR-4743: FlexCache im ONTAP
+
https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf["https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf"^]





== Podcasts

* Folge 263 des Tech OnTap Podcasts: Virtualisierung in ONTAP – Herbst 2020
+
https://soundcloud.com/techontap_podcast/episode-263-virtualization-in-ontap-fall-2020-update["https://soundcloud.com/techontap_podcast/episode-263-virtualization-in-ontap-fall-2020-update"^]

* Folge 264 des Tech OnTap Podcasts: NetApp ONTAP SnapDiff
+
https://soundcloud.com/techontap_podcast/episode-264-netapp-ontap-snapdiff["https://soundcloud.com/techontap_podcast/episode-264-netapp-ontap-snapdiff"^]

* Folge 265 des Tech OnTap Podcasts: NetApp SnapMirror Cloud mit ProLion
+
https://soundcloud.com/techontap_podcast/episode-265-netapp-snapmirror-cloud-featuring-prolion["https://soundcloud.com/techontap_podcast/episode-265-netapp-snapmirror-cloud-featuring-prolion"^]

* Folge 266 des Tech OnTap Podcasts: NetApp ONTAP System Manager 9.8
+
https://soundcloud.com/techontap_podcast/episode-266-netapp-system-manager-98["https://soundcloud.com/techontap_podcast/episode-266-netapp-system-manager-98"^]

* Folge 267 des Tech OnTap Podcasts: SnapMirror Business Continuity
+
https://soundcloud.com/techontap_podcast/episode-267-snapmirror-business-continuity-sm-bc-for-ontap-98["https://soundcloud.com/techontap_podcast/episode-267-snapmirror-business-continuity-sm-bc-for-ontap-98"^]


